-- PostgreSQL
-- PHONE_CATALOG

CREATE TABLE PHONE_CATALOG (
    PHONE_ID SERIAL PRIMARY KEY,
    PHONE_NAME VARCHAR(255) NOT NULL,
    COUNTRY VARCHAR(100) NOT NULL,
    DATE_DELIVERY DATE NOT NULL,
    QUANTITY INTEGER NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    COLOR VARCHAR(50) NOT NULL,
    INSTALLMENT CHAR(1) CHECK(INSTALLMENT IN ('Y', 'N')) NOT NULL,
    INITIAL_PAYMENT DECIMAL(10,2)
);

-- USAGE_FILE_HISTORY

CREATE TABLE USAGE_FILE_HISTORY (
    FILE_ID SERIAL PRIMARY KEY,
    FILE_NAME VARCHAR(255) UNIQUE NOT NULL,
    FILE_DATE TIMESTAMP NOT NULL
);

-- USAGE_DATA_HISTORY

CREATE TABLE USAGE_DATA_HISTORY (
    PARTY_ID VARCHAR(50) NOT NULL,
    OTHER_PARTY_ID VARCHAR(50),
    SERVICE_ID INTEGER CHECK(SERVICE_ID IN (1, 2, 3)) NOT NULL,
    CALL_DATE TIMESTAMP NOT NULL,
    CALL_DURATION INTEGER,
    TOTAL_VOLUME INTEGER,
    CHARGED_DATE TIMESTAMP NOT NULL,
    CHARGE_AMOUNT DECIMAL(10,2) NOT NULL,
    DISCOUNT_AMOUNT DECIMAL(10,2) DEFAULT 0,
    FILE_ID INTEGER,
    FOREIGN KEY (FILE_ID) REFERENCES USAGE_FILE_HISTORY(FILE_ID)
);

-- REF_TARIFF

CREATE TABLE REF_TARIFF (
    RATE_PLAN_ID SERIAL PRIMARY KEY,
    MONTHLY_FEE DECIMAL(10,2) NOT NULL,
    CALL_TARIFF DECIMAL(10,2) NOT NULL,
    SMS_TARIFF DECIMAL(10,2) NOT NULL,
    INTERNET_TARIFF DECIMAL(10,2) NOT NULL,
    TARIFF_DATE DATE NOT NULL
);

-- OPERATION_LOG

CREATE TABLE OPERATION_LOG (
    ID SERIAL PRIMARY KEY,
    OPERATION_TYPE VARCHAR(50) NOT NULL,
    TABLE_NAME VARCHAR(100) NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP,
    STATUS CHAR(1) CHECK(STATUS IN ('P', 'D', 'F')) NOT NULL,
    MESSAGE TEXT
);

-- Индексы для улучшения производительности

CREATE INDEX idx_phone_catalog_date_delivery ON PHONE_CATALOG(DATE_DELIVERY);
CREATE INDEX idx_phone_catalog_color ON PHONE_CATALOG(COLOR);
CREATE INDEX idx_phone_catalog_installment ON PHONE_CATALOG(INSTALLMENT);

CREATE INDEX idx_usage_data_history_party_id ON USAGE_DATA_HISTORY(PARTY_ID);
CREATE INDEX idx_usage_data_history_call_date ON USAGE_DATA_HISTORY(CALL_DATE);
CREATE INDEX idx_usage_data_history_service_id ON USAGE_DATA_HISTORY(SERVICE_ID);
CREATE INDEX idx_usage_data_history_file_id ON USAGE_DATA_HISTORY(FILE_ID);

CREATE INDEX idx_usage_file_history_file_date ON USAGE_FILE_HISTORY(FILE_DATE);

CREATE INDEX idx_operation_log_status ON OPERATION_LOG(STATUS);
CREATE INDEX idx_operation_log_table_name ON OPERATION_LOG(TABLE_NAME);
